### ISSUE TITLE
build broken

### ISSUE THREAD

**Issue by stopfstedt** [jwentworth/agot-setup-analyzer#3]
i'm trying to spin this up from  `master`/HEAD, but no dice so far.

```bash
$ gulp 
[12:15:48] Using gulpfile ~/dev/projects/agot-setup-analyzer/gulpfile.js
[12:15:48] Starting 'scripts'...
gulp-typescript: ts(tsProject) has been deprecated - use .pipe(tsProject()) instead
  As of gulp-typescript 3.0, .pipe(ts(tsProject)) should be written as .pipe(tsProject()).
  More information: http://dev.ivogabe.com/gulp-typescript-3/
js/components/simulationStats.tsx(434,7): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type '((...items: any[]) => number) | ((...items: string[][]) => number)' has no compatible call signatures.
js/components/simulationStats.tsx(435,7): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type '((...items: any[]) => number) | ((...items: string[][]) => number)' has no compatible call signatures.
/home/stefan/dev/projects/agot-setup-analyzer/typings/react/react.d.ts(119,11): error TS2559: Type 'Component<P, S>' has no properties in common with type 'ComponentLifecycle<P, S>'.
[12:15:50] TypeScript: 3 semantic errors
[12:15:50] TypeScript: emit succeeded (with errors)
[12:15:50] Finished 'scripts' after 1.88 s
[12:15:50] Starting 'default'...
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module './components/DeckImport' from '/home/stefan/dev/projects/agot-setup-analyzer/build'
    at /home/stefan/dev/projects/agot-setup-analyzer/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/home/stefan/dev/projects/agot-setup-analyzer/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/stefan/dev/projects/agot-setup-analyzer/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/stefan/dev/projects/agot-setup-analyzer/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
```

here's my node/gulp/typescript versions installed:

```
$ node --version
v8.1.4

$ gulp --version
[12:18:19] CLI version 3.9.1
[12:18:19] Local version 3.9.1

$ npm list typescript
/home/stefan/dev/projects/agot-setup-analyzer
└── typescript@2.6.1 
```

i got past the deprecation warnings by pinning `gulp-typescript` to the the `2.x` branch, but the build is still broken.

```bash
$ npm list gulp-typescript
/home/stefan/dev/projects/agot-setup-analyzer
└── gulp-typescript@2.14.1 

$ gulp
[12:21:00] Using gulpfile ~/dev/projects/agot-setup-analyzer/gulpfile.js
[12:21:00] Starting 'scripts'...
[12:21:01] Finished 'scripts' after 1.26 s
[12:21:01] Starting 'default'...
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module './components/Simulation' from '/home/stefan/dev/projects/agot-setup-analyzer/build'
    at /home/stefan/dev/projects/agot-setup-analyzer/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/home/stefan/dev/projects/agot-setup-analyzer/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/stefan/dev/projects/agot-setup-analyzer/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/stefan/dev/projects/agot-setup-analyzer/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
```

please advise, thanks!

**Comment by jwentworth** [comment]
Ah! I've forgotten about this, I'll take a look this week

**Comment by stopfstedt** [comment]
superseded by https://github.com/jwentworth/agot-setup-analyzer/pull/4
